export const Api_Key = " f6c13184435fc3a20caac9d409e437bc";
export const  API_KEY ="?api_key=f6c13184435fc3a20caac9d409e437bc";
export const  BASE_URL_MOVIE = "http://api.themoviedb.org/3/movie";
export const  BASE_URL_TVSHOW = "http://api.themoviedb.org/3/tv";
export const  IMAGE_BASE_URL = "http://image.tmdb.org/t/p/w185/";
export const  POPULAR_URL_MOVIE = BASE_URL_MOVIE+"/popular"+movieConstants.API_KEY;
export const  TOP_RATED_URL_MOVIE = BASE_URL_MOVIE+"/top_rated"+movieConstants.API_KEY;
export const  POPULAR_URL_TVSHOW = BASE_URL_TVSHOW+"/popular"+movieConstants.API_KEY;
export const  TOP_RATED_URL_TVSHOW = BASE_URL_TVSHOW+"/top_rated"+movieConstants.API_KEY;
export const  SEARCH_MOVIE = "https://api.themoviedb.org/3/search/movie"+movieConstants.API_KEY;
export const  POPULARITY = "popularity";
export const  RATING = "rating";
